config/routes.rb
Rails.application.routes.draw do


  resources :dant_faixa_etaria
  devise_for :users
  scope "/usuario" do
  resources :users do
    collection do
      get "home"
      get "alterar_senha"
    end
  end
  end
  resources :condutas
  resources :diagnosticos
  resources :sinais_sintomas
  resources :dermatologicas
  resources :recidivas
  resources :categoria_queixas
  resources :avaliacao_sensitivas do
    member do
      get "inserir_marcacao"
    end
    collection do
      get "remover_marcacao"
    end
  end
  resources :episodio_reacionals
  resources :avaliacao_neurologicas
  resources :classificacao_graus
  resources :avaliacao_notificacaos
  resources :esquema_substitutivos
  resources :contato_avaliacaos
  resources :bcgs
  resources :notificacao_contatos
  resources :dados_clinicos
  resources :notificacaos do
    collection do
      get 'home'
      get 'avaliacao_pendente'
    end
    member do
      get "recidiva"
    end
  end
  resources :pacientes do
    collection do
      get "mapa"
    end
  end
  resources :medicamentos
  resources :queixas
  resources :monofilamentos
  resources :ocupacaos
  resources :cidades

  resources :escala_parts
  resources :escala_salsas
  resources :monthly_reports

  scope "/dant" do
    resources :dant_questions
    resources :dant_requests do
      member do
        get "enviar"
        get "faixa_etaria"
        get "alterar_status"
      end
      collection do
        get "dashboard"
        get "cidade_change"
      end
    end
    resources :dant_responsavel_programs
    resources :dant_regions
    resources :dant_pacients


  end

  scope "/imunizacao" do
    resources :imunizacao_encerramentos
    resources :imunizacao_esquemas do
      member do
        get "novo_encerramento"
        get "nao_aplicado"
      end
    end
    resources :imunizacao_imunobiologicos do
      member do
        get "nova_dose"
        get "indeferir"
      end
    end
    resources :imunizacao_vacinas do
      member do
        get "retornarIndicacoes"
      end
      collection do
        get "relatorio"
      end
    end
    resources :imunizacao_solicitacaos
    resources :imunizacao_indications do
      member do
        get "retornar_vacinas"
      end
    end
  end

  scope  "/dst" do
    resources :dst_questionarios
    resources :dst_movimentacaos do
      collection do
        get "atender"
        get "finalizar_atendimento"
      end
    end
    resources :dst_solicitacao_produtos
    resources :dst_solicitacaos do
      member do
        get "autorizar"
        get "recusar"
      end
      collection do
        get "mapa"
      end
    end
    resources :dst_lotes
    resources :dst_locals
    resources :dst_produtos do
      member do
        get "lotes_ajax"
      end
    end
  end

  root "users#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notificacao.rb
# == Schema Information
#
# Table name: notificacaos
#
#  id                       :integer          not null, primary key
#  numero                   :string
#  data                     :date
#  grau_incapacidade        :string
#  modo_entrada             :string
#  modo_deteccao            :string
#  observacoes              :string
#  baciloscopia             :string
#  data_inicio              :date
#  esquema_terapeutico      :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  paciente_id              :integer
#  recidiva_id              :integer
#  avaliacao_notificacao_id :integer
#
# Indexes
#
#  index_notificacaos_on_avaliacao_notificacao_id  (avaliacao_notificacao_id)
#  index_notificacaos_on_paciente_id               (paciente_id)
#  index_notificacaos_on_recidiva_id               (recidiva_id)
#
# Foreign Keys
#
#  fk_rails_...  (avaliacao_notificacao_id => avaliacao_notificacaos.id)
#  fk_rails_...  (paciente_id => pacientes.id)
#  fk_rails_...  (recidiva_id => recidivas.id)
#

class Notificacao < ApplicationRecord
  belongs_to :paciente
  belongs_to :recidiva, optional: true
  belongs_to :avaliacao_notificacao, optional: true

  has_many :dados_clinicos, dependent: :destroy
  has_many :notificacao_contatoes, dependent: :destroy
  has_many :avaliacao_notificacaos, dependent: :destroy
  has_many :esquema_substitutivos, dependent: :destroy
  has_many :episodio_reacionals, dependent: :destroy
  has_many :avaliacao_sensitivas
  has_many :recidivas

  accepts_nested_attributes_for :dados_clinicos, allow_destroy: true
  accepts_nested_attributes_for :notificacao_contatoes, allow_destroy: true
  accepts_nested_attributes_for :avaliacao_notificacaos, allow_destroy: true
  accepts_nested_attributes_for :esquema_substitutivos, allow_destroy: true
  accepts_nested_attributes_for :episodio_reacionals, allow_destroy: true
  accepts_nested_attributes_for :avaliacao_sensitivas, allow_destroy: true
  accepts_nested_attributes_for :recidivas, allow_destroy: true

  extend Enumerize

  enumerize :grau_incapacidade, in: [:grau_0, :grau_1,:grau_2,:nao_avaliado], predicates: true
  enumerize :modo_entrada, in: [:caso_novo, :outra_unidade,:outro_municipio,:outro_estado,:outro_pais,:recidiva,:outros_reingressos], predicates: true
  enumerize :modo_deteccao, in: [:encaminhamento, :demanda_expontanea,:exame_coletividade,:exame_contatos,:outros_modos], predicates: true
  enumerize :baciloscopia, in: [:positivo, :negativo,:nao_realizado], predicates: true
  enumerize :esquema_terapeutico, in: [:pb_infantil, :pb_adulto,:mb_infantil,:mb_adulto,:outros_esquemas], predicates: true

  validates_presence_of Notificacao.attribute_names - %w(id created_at updated_at observacoes recidiva_id avaliacao_notificacao_id)
  validates_presence_of :dados_clinicos,:notificacao_contatoes#,:avaliacao_notificacaos

  #Método que retorna o nome do objeto
  def to_s
    self.numero
  end
end

app/controllers/notificacaos_controller.rb
#Classe que controla as açoes da Notificacao
class NotificacaosController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_notificacao, only: [:show, :edit, :update, :destroy,:recidiva]
  before_action :set_combos, only: [:new, :edit, :create,:update]

  # GET /notificacaos
  def index
    if current_user.administrador?
      @q = Notificacao.all.ransack(params[:q])
    else
      @q = Notificacao.includes(:paciente).where(pacientes: {cidade: current_user.cidade}).ransack(params[:q])
    end

    @notificacaos = @q.result.page(params[:page])
  end

  #Método que apresenta a home
  def home
    @pacientes = Paciente.all
    @notificacoes = Notificacao.all
    @contatos = NotificacaoContato.all
    @incidencia = Cidade.order(pacientes_count: :desc).first
  end

  # GET /notificacaos/1
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Notificacao-#{@notificacao.numero}"
      end
    end
  end

  #Método que retorna as notificações com avaliações pendentes
  def avaliacao_pendente
    if current_user.administrador?
      notificacoes = Notificacao.includes(:paciente,:avaliacao_notificacaos).all
    else
      notificacoes = Notificacao.includes(:paciente,:avaliacao_notificacaos).where(pacientes: {cidade: current_user.cidade})
    end
    @pendentes = []
    notificacoes.each do |n|
      meses = (DateTime.now.year * 12 + DateTime.now.month) - (n.data_inicio.year * 12 + n.data_inicio.month)
      if (meses >=3 and meses < 6) and n.avaliacao_notificacaos.size < 1
        @pendentes << n
      end
      if (meses >=6 and meses < 9) and n.avaliacao_notificacaos.size < 2
        @pendentes << n
      end
      if (meses >=9 and meses < 12) and n.avaliacao_notificacaos.size < 3
        @pendentes << n
      end
      if meses >= 12  and n.avaliacao_notificacaos.size < 4
        @pendentes << n
      end

    end
  end

  # GET /notificacaos/new
  def new
    @notificacao = Notificacao.new(paciente_id: params[:paciente])
    if params[:recidiva].present?
      @notificacao.recidiva_id = params[:recidiva]
      @notificacao.modo_entrada = :recidiva
    end
    if params[:avaliacao].present?
      @notificacao.avaliacao_notificacao_id = params[:avaliacao]
    end
  end

  # GET /notificacaos/1/edit
  def edit
  end

  # POST /notificacaos
  def create
    @notificacao = Notificacao.new(notificacao_params)

    if @notificacao.save
      redirect_to @notificacao.paciente, notice: 'Notificação criada com sucesso!'
    else
      render :new
    end
  end

  #Método utilizado para criar uma recidiva ou abrir a existente
  def recidiva
    recidiva = @notificacao.recidivas.first
    if recidiva
      redirect_to recidiva_path(recidiva)
    else
      redirect_to new_recidiva_path(notificacao: @notificacao.id)
    end

  end

  # PATCH/PUT /notificacaos/1
  def update
    if @notificacao.update(notificacao_params)
      redirect_to @notificacao, notice: 'Notificacao was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /notificacaos/1
  def destroy
    @notificacao.destroy
    redirect_to notificacaos_url, notice: 'Notificacao was successfully destroyed.'
  end

  private

  #Método utilizado para setar os objetos utilizados no formulário
  def set_combos
    @graus_incapacidade = Notificacao.grau_incapacidade.options
    @modos_entrada = Notificacao.modo_entrada.options
    @modos_deteccao = Notificacao.modo_deteccao.options
    @baciloscopias = Notificacao.baciloscopia.options
    @esquemas = Notificacao.esquema_terapeutico.options
    @medicamentos = Medicamento.all.sort_by{|a| a.nome}.map{|a| [a.nome,a.id]}
    @tipos_contato = NotificacaoContato.tipo_contato.options
    @formas_clinicas = DadosClinico.forma_clinica.options
    @classificacoes_operacional = DadosClinico.classificacao_operacional.options
    @episodios_reacionais = EpisodioReacional.tipo.options
    @classificacoes_operacionais = AvaliacaoNotificacao.classificacao_operacional.options
    @queixas = Queixa.all.group_by(&:categoria)#.map{|a| [a.nome,a.id]}
    @categorias = Queixa.categoria.options
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_notificacao
      @notificacao = Notificacao.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def notificacao_params
      params.require(:notificacao).permit(:avaliacao_notificacao_id,:recidiva_id,:paciente_id,:numero, :data, :grau_incapacidade, :modo_entrada, :modo_deteccao, :observacoes, :baciloscopia, :data_inicio, :esquema_terapeutico,
                                          esquema_substitutivos_attributes:[:id,:notificacao_id,:miligramas,:medicamento_id,:_destroy],
                                          notificacao_contatoes_attributes:[:bcg_primeira,:bcg_segunda,:bcg_cicatriz,:id,:notificacao_id,:nome,:tipo_contato,:suspeito,:confirmado,:_destroy],
      dados_clinicos_attributes:[:id,:notificacao_id,:lesoes_cultaneas,:forma_clinica,:classificacao_operacional,:nervos_afetados,:_destroy],
                                          episodio_reacionals_attributes:[:id,:notificacao_id,:tipo,:numero_episodios,:conduta_mendicamentosa,:data_inicio,:data_termino,:_destroy],
      recidiva_attributes:[:id,:unidade_saude, :prontuario, :data_diagnostico, :classificacao_operacional, :forma_clinica, :baciloscopia, :baciloscopia_lb, :grau_incapacidade,
                           :inicio_tratamento, :esquema_terapeutico, :tempo_tratamento, :doses,
                           :regularidade, :termino_tratamento, :tratamento_observacoes, :tempo_alta_cura,
                           :data_primeiros_sintomas, :baciloscopia_alta, :baciloscopia_lb_alta,
                           :grau_incapacidade_alta, :classificacao_operacional_alta, :notificacao_id,:_destroy],
      avaliacao_notificacaos_attributes:[:id,:classificacao_operacional, :inicio_pqt, :alta_pqt, :profissao, :unidade_saude, :atividades_realizadas_ubs, :grupo_autocuidado, :encaminhamentos,
                                         :imobilizacoes, :adaptacoes, :observacoes, :notificacao_id,:_destroy,
                                         avaliacao_neurologicas_attributes:[:id,:avaliacao_notificacao_id,:data,:olhos_sem_forca_d,:olhos_sem_forca_e,:olhos_com_forca_d,:olhos_com_forca_e,:triquiase_d,:triquiase_e,:ectropio_d,:ectropio_e,:catarata_d,:catarata_e,:sensibilidade_cornea_d,:sensibilidade_cornea_e,:opacidade_corneana_d,:opacidade_corneana_e,:acuidade_visual_d,:acuidade_visual_e,:ressecamento_d,:ressecamento_e,:feridas_d,:feridas_e,:perfuracao_septo_d,:perfuracao_septo_e,:nervo_radial_d,:nervo_radial_e,:nervo_ulnar_d,:nervo_ulnar_e,:nervo_mediano_d,:nervo_mediano_e,:abducao_5_dedo_d,:abducao_5_dedo_e,:abducao_polegar_d,:abducao_polegar_e,:extensores_punho_d,:extensores_punho_e,:nervo_fibular_d,:nervo_fibular_e,:nervo_tibial_d,:nervo_tibial_e,:extensao_halux_d,:extensao_halux_e,:dorsiflexao_pe_d,:dorsiflexao_pe_e,:_destroy],
                                         classificacao_graus_attributes:[:id,:avaliacao_notificacao_id,:data,:olho_direito,:olho_esquerdo,:mao_direita,:mao_esqueda,:pe_direito,:pe_esquerdo,:maior_grau,:escore_omp,:_destroy]])
    end
end

app/helpers/notificacaos_helper.rb
#Disponibiliza métodos para serem usados nas views
module NotificacaosHelper
end

app/views/notificacaos/_avaliacao_completa.html.erb
<div class="card-panel">


	<div class="row">
    <div class="col s12 l4">
      <strong>Classificação Operacional:</strong>
      <%= avaliacao_notificacao.classificacao_operacional_text %>
    </div >

    <div class="col s6 l4">
      <strong>Inicio PQT:</strong>
      <%= avaliacao_notificacao.inicio_pqt %>
    </div>

    <div class="col s6 l4">
      <strong>Alta PQT:</strong>
      <%= avaliacao_notificacao.alta_pqt %>
    </div>
  </div>
<p>
  <strong>Profissão:</strong>
  <%= avaliacao_notificacao.profissao %>
</p>

<p>
  <strong>Unidade de saúde:</strong>
  <%= avaliacao_notificacao.unidade_saude %>
</p>
<div class="row">
  <div class="col s12 l4">
    <strong>Atividades Orientadas:</strong>
    <%= avaliacao_notificacao.atividades_orientadas == true ? "SIM" : "NÃO" %>
  </div>
  <div class="col s12 l4">
    <strong>Atividades realizadas na UBS:</strong>
    <%= avaliacao_notificacao.atividades_realizadas_ubs == true ? "SIM" : "NÃO" %>
  </div>

  <div class="col s12 l4">
    <strong>Participação em grupo de autocuidado:</strong>
    <%= avaliacao_notificacao.grupo_autocuidado == true ? "SIM" : "NÃO" %>
  </div>

</div>
<p>
  <strong>Encaminhamentos:</strong>
  <%= avaliacao_notificacao.encaminhamentos %>
</p>

<p>
  <strong>Imobilizações:</strong>
  <%= avaliacao_notificacao.imobilizacoes %>
</p>

<p>
  <strong>Adaptações:</strong>
  <%= avaliacao_notificacao.adaptacoes %>
</p>

<p>
  <strong>Observações:</strong>
  <%= avaliacao_notificacao.observacoes %>
</p>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Avaliações Neurológicas</span>
        <%= render partial: "avaliacao_notificacaos/avaliacao_neurologica", locals:{avaliacao_neurologicas: avaliacao_notificacao.avaliacao_neurologicas} %>
      </div>

    </div>
  </div>

  <br>
  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Classificação do Grau de Incapacidade</span>
        <%= render partial: "avaliacao_notificacaos/classificacao_grau", locals:{classificacao_graus: avaliacao_notificacao.classificacao_graus} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Avaliações Sensitivas</span>
        <%= render partial: "avaliacao_notificacaos/avaliacao_sensitiva_print", locals:{avaliacao_sensitivas: avaliacao_notificacao.avaliacao_sensitivas} %>
      </div>

    </div>
  </div>

</div>

app/views/notificacaos/_avaliacoes.html.erb
<table class="card striped responsive-table">
  <thead>
  <tr>
    <th>Classificação operacional</th>
    <th>Início PQT</th>
    <th>Alta PQT</th>
    <th>Unidade saúde</th>

  </tr>
  </thead>

  <tbody>
  <% avaliacao_notificacaos.each do |avaliacao_notificacao| %>
      <tr>

        <td><%= link_to avaliacao_notificacao.classificacao_operacional_text,avaliacao_notificacao %></td>



        <td><%= avaliacao_notificacao.inicio_pqt %></td>



        <td><%= avaliacao_notificacao.alta_pqt %></td>



        <td><%= avaliacao_notificacao.unidade_saude %></td>





      </tr>
  <% end %>
  </tbody>
</table>

app/views/notificacaos/_contatos.html.erb
<table class="card striped responsive-table">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Tipo contato</th>
    <th>Suspeito</th>
    <th>Confirmado</th>
  </tr>
  </thead>

  <tbody>
  <% notificacao_contatos.each do |notificacao_contato| %>
      <tr>

        <td><%= link_to notificacao_contato.nome, notificacao_contato %></td>



        <td><%= notificacao_contato.tipo_contato_text %></td>



        <td><%= notificacao_contato.suspeito == true ? "SIM" : "NÃO" %></td>



        <td><%= notificacao_contato.confirmado == true ? "SIM" : "NÃO" %></td>


      </tr>
  <% end %>
  </tbody>
</table>

app/views/notificacaos/index.html.erb
<div class="card">
  <h1 class="center-align">Notificações</h1>
</div>
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
          <%= f.text_field :numero_or_paciente_nome_cont, placeholder: "Número, Paciente" %>
          <div class="row">
            <div class="col s12 l2">
              <label >Grau</label>
              <%= f.select :grau_incapacidade_eq, Notificacao.grau_incapacidade.options,{include_blank:true},{class:"browser-default select2"} %>
            </div>
            <div class="col s12 l2">
              <label >Entrada</label>
              <%= f.select :modo_entrada_eq, Notificacao.modo_entrada.options,{include_blank:true},{class:"browser-default select2"} %>
            </div>
            <div class="col s12 l2">
              <label >Detecção</label>
              <%= f.select :modo_deteccao_eq, Notificacao.modo_deteccao.options,{include_blank:true},{class:"browser-default select2"} %>
            </div>
            <div class="col s12 l2">
              <label >Baciloscopia</label>
              <%= f.select :baciloscopia_eq, Notificacao.baciloscopia.options,{include_blank:true},{class:"browser-default select2"} %>
            </div>
            <div class="col s12 l2">
              <label >Esquema</label>
              <%= f.select :esquema_terapeutico_eq, Notificacao.esquema_terapeutico.options,{include_blank:true},{class:"browser-default select2"} %>
            </div>
          </div>
          <br>
          <%= f.submit "Filtrar", class:"btn" %>
      <% end %>
    </div>
  </div>
</div>

<table class="card striped responsive-table">
  <thead>
  <tr>
    <th>Número</th>
    <th>Paciente</th>
    <th>Data</th>
    <th>Grau incapacidade</th>
    <th>Modo entrada</th>
    <th>Modo detecção</th>
    <th>Baciloscopia</th>
    <th>Data início</th>
    <th>Esquema terapêutico</th>
  </tr>
  </thead>

  <tbody>
  <% @notificacaos.each do |notificacao| %>
      <tr>

        <td><%= link_to notificacao.numero,notificacao %></td>

        <td><%= link_to notificacao.paciente,notificacao.paciente %></td>


        <td><%= notificacao.data %></td>



        <td><%= notificacao.grau_incapacidade_text %></td>



        <td><%= notificacao.modo_entrada_text %></td>



        <td><%= notificacao.modo_deteccao_text %></td>



        <td><%= notificacao.baciloscopia_text %></td>



        <td><%= notificacao.data_inicio %></td>



        <td><%= notificacao.esquema_terapeutico_text %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@notificacaos)  %>
</div>

<%= link_to '+ Cadastrar', new_notificacao_path, class:"btn" %>

app/views/notificacaos/show.html.erb
<%= render partial: "layouts/cabecalho_print" %>

<br>
<div class="no-print">
<%= link_to 'Nova Avaliação', new_avaliacao_notificacao_path(notificacao: @notificacao.id), class:"btn" %>
</div>
<%#= link_to 'Ficha de Suspeita de Recidiva', recidiva_notificacao_path(@notificacao), class:"btn" %>

<div class="card-panel">

  <div class="row">
    <div class="col s6">
      <strong>Paciente:</strong>
      <%= @notificacao.paciente %>
    </div>
    <div class="col s6">
      <strong>Idade:</strong>
      <%= @notificacao.paciente.idade %>
    </div>
    <div class="col s6">
      <strong>Sexo:</strong>
      <%= @notificacao.paciente.sexo == 1 ? "Masculino" : "Feminino"  %>
    </div>
    <div class="col s6">
      <strong>Cidade:</strong>
      <%= @notificacao.paciente.cidade%>
    </div>
  </div>
  <br>
	<div class="row">
    <div class="col s6">
      <strong>Numero:</strong>
      <%= @notificacao.numero %>
    </div>

    <div class="col s6">
      <strong>Data:</strong>
      <%= @notificacao.data %>
    </div>
  </div>
  <div class="row">
    <div class="col s6 l3">
      <strong>Grau incapacidade:</strong>
      <%= @notificacao.grau_incapacidade_text %>
    </div>
    <div class="col s6 l3">
      <strong>Modo de entrada:</strong>
      <%= @notificacao.modo_entrada_text %>
    </div>
    <div class="col s6 l4">
      <strong>Modo de deteccao:</strong>
      <%= @notificacao.modo_deteccao_text %>
    </div>
    <div class="col s6 l2">
      <strong>Baciloscopia:</strong>
      <%= @notificacao.baciloscopia_text %>
    </div>

  </div>

  <div class="row">
    <div class="col s6 l4">
      <strong>Data de início do Tratamento:</strong>
      <%= @notificacao.data_inicio %>
    </div>
    <div class="col s6 l3">
      <strong>Esquema terapêutico:</strong>
      <%= @notificacao.esquema_terapeutico_text %>
    </div>
  </div>

<p>
  <strong>Observações:</strong>
  <%= @notificacao.observacoes %>
</p>


  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Esquema Substitutivo</span>
        <%= render partial: "esquemas_substitutivo", locals:{esquema_substitutivos: @notificacao.esquema_substitutivos} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Episódios Reacionais</span>
        <%= render partial: "episodios_relacionais", locals:{episodio_reacionals: @notificacao.episodio_reacionals} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Dados Clínicos</span>
        <%= render partial: "dados_clinicos", locals:{dados_clinicos: @notificacao.dados_clinicos} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Contatos</span>
        <%= render partial: "contatos", locals:{notificacao_contatos: @notificacao.notificacao_contatoes} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Avaliações</span>
        <div class="no-print">
        <%= render partial: "avaliacoes", locals:{avaliacao_notificacaos: @notificacao.avaliacao_notificacaos} %>
        </div>
        <div class="print">
          <% @notificacao.avaliacao_notificacaos.each do |a| %>
              <%= render partial: "avaliacao_completa", locals:{avaliacao_notificacao: a} %>
          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>
<div class="no-print">
<%= link_to 'Voltar', notificacaos_path, class:"btn" %>
  <a href="" onclick="window.print();" class="btn">Imprimir</a>
</div>

app/views/notificacaos/show.pdf.erb
<br>

<div class="card-panel">
	<div class="row">
    <div class="col s6">
      <strong>Numero:</strong>
      <%= @notificacao.numero %>
    </div>

    <div class="col s6">
      <strong>Data:</strong>
      <%= @notificacao.data %>
    </div>
  </div>

<p>
  <strong>Grau incapacidade:</strong>
  <%= @notificacao.grau_incapacidade_text %>
</p>

<p>
  <strong>Modo de entrada:</strong>
  <%= @notificacao.modo_entrada_text %>
</p>

<p>
  <strong>Modo de deteccao:</strong>
  <%= @notificacao.modo_deteccao_text %>
</p>

<p>
  <strong>Observações:</strong>
  <%= @notificacao.observacoes %>
</p>

<p>
  <strong>Baciloscopia:</strong>
  <%= @notificacao.baciloscopia_text %>
</p>

<p>
  <strong>Data de início do Tratamento:</strong>
  <%= @notificacao.data_inicio %>
</p>

<p>
  <strong>Esquema terapêutico:</strong>
  <%= @notificacao.esquema_terapeutico_text %>
</p>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Esquema Substitutivo</span>
        <%= render partial: "esquemas_substitutivo", locals:{esquema_substitutivos: @notificacao.esquema_substitutivos} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Episódios Reacionais</span>
        <%= render partial: "episodios_relacionais", locals:{episodio_reacionals: @notificacao.episodio_reacionals} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Dados Clínicos</span>
        <%= render partial: "dados_clinicos", locals:{dados_clinicos: @notificacao.dados_clinicos} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Contatos</span>
        <%= render partial: "contatos", locals:{notificacao_contatos: @notificacao.notificacao_contatoes} %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Avaliações</span>
        <%= render partial: "avaliacoes", locals:{avaliacao_notificacaos: @notificacao.avaliacao_notificacaos} %>
      </div>

    </div>
  </div>

</div>
<%= link_to 'Voltar', notificacaos_path, class:"btn" %>