config/routes.rb
Rails.application.routes.draw do


  resources :dant_faixa_etaria
  devise_for :users
  scope "/usuario" do
  resources :users do
    collection do
      get "home"
      get "alterar_senha"
    end
  end
  end
  resources :condutas
  resources :diagnosticos
  resources :sinais_sintomas
  resources :dermatologicas
  resources :recidivas
  resources :categoria_queixas
  resources :avaliacao_sensitivas do
    member do
      get "inserir_marcacao"
    end
    collection do
      get "remover_marcacao"
    end
  end
  resources :episodio_reacionals
  resources :avaliacao_neurologicas
  resources :classificacao_graus
  resources :avaliacao_notificacaos
  resources :esquema_substitutivos
  resources :contato_avaliacaos
  resources :bcgs
  resources :notificacao_contatos
  resources :dados_clinicos
  resources :notificacaos do
    collection do
      get 'home'
      get 'avaliacao_pendente'
    end
    member do
      get "recidiva"
    end
  end
  resources :pacientes do
    collection do
      get "mapa"
    end
  end
  resources :medicamentos
  resources :queixas
  resources :monofilamentos
  resources :ocupacaos
  resources :cidades

  resources :escala_parts
  resources :escala_salsas
  resources :monthly_reports

  scope "/dant" do
    resources :dant_questions
    resources :dant_requests do
      member do
        get "enviar"
        get "faixa_etaria"
        get "alterar_status"
      end
      collection do
        get "dashboard"
        get "cidade_change"
      end
    end
    resources :dant_responsavel_programs
    resources :dant_regions
    resources :dant_pacients


  end

  scope "/imunizacao" do
    resources :imunizacao_encerramentos
    resources :imunizacao_esquemas do
      member do
        get "novo_encerramento"
        get "nao_aplicado"
      end
    end
    resources :imunizacao_imunobiologicos do
      member do
        get "nova_dose"
        get "indeferir"
      end
    end
    resources :imunizacao_vacinas do
      member do
        get "retornarIndicacoes"
      end
      collection do
        get "relatorio"
      end
    end
    resources :imunizacao_solicitacaos
    resources :imunizacao_indications do
      member do
        get "retornar_vacinas"
      end
    end
  end

  scope  "/dst" do
    resources :dst_questionarios
    resources :dst_movimentacaos do
      collection do
        get "atender"
        get "finalizar_atendimento"
      end
    end
    resources :dst_solicitacao_produtos
    resources :dst_solicitacaos do
      member do
        get "autorizar"
        get "recusar"
      end
      collection do
        get "mapa"
      end
    end
    resources :dst_lotes
    resources :dst_locals
    resources :dst_produtos do
      member do
        get "lotes_ajax"
      end
    end
  end

  root "users#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/avaliacao_sensitiva.rb
# == Schema Information
#
# Table name: avaliacao_sensitivas
#
#  id                       :integer          not null, primary key
#  avaliacao_notificacao_id :integer
#  data                     :date
#  dedao_direito            :integer
#  indicador_d_ponta        :integer
#  indicador_d              :integer
#  mindinho_d_ponta         :integer
#  mindinho_d               :integer
#  mao_direita              :integer
#  mao_d_costa              :integer
#  dedao_esquerdo           :integer
#  indicador_e_ponta        :integer
#  indicador_e              :integer
#  mindinho_e_ponta         :integer
#  mindinho_e               :integer
#  mao_esquerda             :integer
#  mao_e_costa              :integer
#  pe_direito               :integer
#  pe_d_1_ponta             :integer
#  pe_d_3_ponta             :integer
#  pe_d_5_ponta             :integer
#  pe_d_1                   :integer
#  pe_d_3                   :integer
#  pe_d_5                   :integer
#  pe_d_e1                  :integer
#  pe_d_calcanhar           :integer
#  pe_esquerdo              :integer
#  pe_e_1_ponta             :integer
#  pe_e_3_ponta             :integer
#  pe_e_5_ponta             :integer
#  pe_e_1                   :integer
#  pe_e_3                   :integer
#  pe_e_5                   :integer
#  pe_e_e1                  :integer
#  pe_e_e2                  :integer
#  pe_e_calcanhar           :integer
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  pe_d_e2                  :integer
#
# Indexes
#
#  index_avaliacao_sensitivas_on_avaliacao_notificacao_id  (avaliacao_notificacao_id)
#
# Foreign Keys
#
#  fk_rails_...  (avaliacao_notificacao_id => avaliacao_notificacaos.id)
#

class AvaliacaoSensitiva < ApplicationRecord
  belongs_to :avaliacao_notificacao
  has_many :marcacaos, dependent: :destroy
  has_one :paciente, through: :avaliacao_notificacao
  has_many :sensitiva_images, dependent: :destroy

  accepts_nested_attributes_for :marcacaos, allow_destroy: true

  validates_presence_of AvaliacaoSensitiva.attribute_names - %w(id created_at updated_at avaliacao_notificacao_id), on: :update
end

app/controllers/avaliacao_sensitivas_controller.rb
#Classe que controla as açoes da avaliação sensitiva
class AvaliacaoSensitivasController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_avaliacao_sensitiva, only: [:show, :edit, :update, :destroy,:inserir_marcacao]
  before_action :set_combos, only: [:new, :edit, :create,:update]

  # GET /avaliacao_sensitivas
  def index
    @q = AvaliacaoSensitiva.all.ransack(params[:q])
    @avaliacao_sensitivas = @q.result.page(params[:page])
  end

  # GET /avaliacao_sensitivas/1
  def show
  end

  #Método que insere a marcação do canvas
  def inserir_marcacao
    marcacao = Marcacao.create(avaliacao_sensitiva_id: @avaliacao_sensitiva.id,imagem: params[:imagem],posicaox: params[:posicaox],posicaoy: params[:posicaoy],membro: params[:membro] )
    render json: {msg:"ok", marcacao: marcacao.to_json}
  end

  #Método que remove a marcação do canvas
  def remover_marcacao

    marcacao = Marcacao.find(params[:marca])
    marcacao.destroy

    avaliacao = marcacao.avaliacao_sensitiva
    avaliacao.dedao_direito = params[:dedao_direito]
    avaliacao.indicador_d_ponta = params[:indicador_d_ponta]
    avaliacao.indicador_d = params[:indicador_d]
    avaliacao.mindinho_d_ponta = params[:mindinho_d_ponta]
    avaliacao.mindinho_d = params[:mindinho_d]
    avaliacao.mao_direita = params[:mao_direita]
    avaliacao.mao_d_costa = params[:mao_d_costa]
    avaliacao.dedao_esquerdo = params[:dedao_esquerdo]
    avaliacao.indicador_e_ponta = params[:indicador_e_ponta]
    avaliacao.indicador_e = params[:indicador_e]
    avaliacao.mindinho_e_ponta = params[:mindinho_e_ponta]
    avaliacao.mindinho_e = params[:mindinho_e]
    avaliacao.mao_esquerda = params[:mao_esquerda]
    avaliacao.mao_e_costa = params[:mao_e_costa]
    avaliacao.pe_direito = params[:pe_direito]
    avaliacao.pe_d_1_ponta = params[:pe_d_1_ponta]
    avaliacao.pe_d_3_ponta = params[:pe_d_3_ponta]
    avaliacao.pe_d_5_ponta = params[:pe_d_5_ponta]
    avaliacao.pe_d_1 = params[:pe_d_1]
    avaliacao.pe_d_3 = params[:pe_d_3]
    avaliacao.pe_d_5 = params[:pe_d_5]
    avaliacao.pe_d_e1 = params[:pe_d_e1]
    avaliacao.pe_d_calcanhar = params[:pe_d_calcanhar]
    avaliacao.pe_esquerdo = params[:pe_esquerdo]
    avaliacao.pe_e_1_ponta = params[:pe_e_1_ponta]
    avaliacao.pe_e_3_ponta = params[:pe_e_3_ponta]
    avaliacao.pe_e_5_ponta = params[:pe_e_5_ponta]
    avaliacao.pe_e_1 = params[:pe_e_1]
    avaliacao.pe_e_3 = params[:pe_e_3]
    avaliacao.pe_e_5 = params[:pe_e_5]
    avaliacao.pe_e_e1 = params[:pe_e_e1]
    avaliacao.pe_e_e2 = params[:pe_e_e2]
    avaliacao.pe_e_calcanhar = params[:pe_e_calcanhar]
    avaliacao.pe_d_e2 = params[:pe_d_e2]
    avaliacao.save(validate: false)

    #redirect_to edit_avaliacao_sensitiva_path(marcacao.avaliacao_sensitiva)
    render json: {msg:"ok"}
  end

  # GET /avaliacao_sensitivas/new
  def new
    @avaliacao_sensitiva = AvaliacaoSensitiva.new(avaliacao_notificacao_id: params[:avaliacao])
    @avaliacao_sensitiva.save
    SensitivaImage.create!(avaliacao_sensitiva: @avaliacao_sensitiva,opcao: 'mao_direita')
    SensitivaImage.create!(avaliacao_sensitiva: @avaliacao_sensitiva,opcao: 'mao_esquerda')
    SensitivaImage.create!(avaliacao_sensitiva: @avaliacao_sensitiva,opcao: 'pe_direito')
    SensitivaImage.create!(avaliacao_sensitiva: @avaliacao_sensitiva,opcao: 'pe_esquerdo')
    redirect_to edit_avaliacao_sensitiva_path(@avaliacao_sensitiva)
  end

  # GET /avaliacao_sensitivas/1/edit
  def edit
  end

  # POST /avaliacao_sensitivas
  def create
    @avaliacao_sensitiva = AvaliacaoSensitiva.new(avaliacao_sensitiva_params)

    if @avaliacao_sensitiva.save
      redirect_to @avaliacao_sensitiva.avaliacao_notificacao, notice: 'Avaliação Sensitiva criada com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /avaliacao_sensitivas/1
  def update
    if @avaliacao_sensitiva.update(avaliacao_sensitiva_params)
      #salva as imagens da avaliacao sensitiva
      unless params[:base64_mao_direita].empty?
        data =  params[:base64_mao_direita]
        img = SensitivaImage.where("avaliacao_sensitiva_id = ? and opcao = ?",@avaliacao_sensitiva.id,'mao_direita').first_or_create(avaliacao_sensitiva: @avaliacao_sensitiva, opcao: 'mao_direita')
        img.imagem = params[:base64_mao_direita]
        img.imagem.recreate_versions!
        img.save
      end
      unless params[:base64_mao_esquerda].empty?
        data =  params[:base64_mao_esquerda]
        img = SensitivaImage.where("avaliacao_sensitiva_id = ? and opcao = ?",@avaliacao_sensitiva.id,'mao_esquerda').first_or_create(avaliacao_sensitiva: @avaliacao_sensitiva, opcao: 'mao_esquerda')
        img.imagem = params[:base64_mao_esquerda]
        img.imagem.recreate_versions!
        img.save
      end
      unless params[:base64_pe_direito].empty?
        data =  params[:base64_pe_direito]
        img = SensitivaImage.where("avaliacao_sensitiva_id = ? and opcao = ?",@avaliacao_sensitiva.id,'pe_direito').first_or_create(avaliacao_sensitiva: @avaliacao_sensitiva, opcao: 'pe_direito')
        img.imagem = params[:base64_pe_direito]
        img.imagem.recreate_versions!
        img.save
      end
      unless params[:base64_pe_esquerdo].empty?
        data =  params[:base64_pe_esquerdo]
        img = SensitivaImage.where("avaliacao_sensitiva_id = ? and opcao = ?",@avaliacao_sensitiva.id,'pe_esquerdo').first_or_create(avaliacao_sensitiva: @avaliacao_sensitiva, opcao: 'pe_esquerdo')
        img.imagem = params[:base64_pe_esquerdo]
        img.imagem.recreate_versions!
        img.save
      end
      redirect_to @avaliacao_sensitiva.avaliacao_notificacao, notice: 'Avaliação Sensitiva atualizada com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /avaliacao_sensitivas/1
  def destroy
    @avaliacao_sensitiva.destroy
    redirect_to @avaliacao_sensitiva.avaliacao_notificacao, notice: 'Avaliação Sensitiva removida com sucesso.'
  end

  private
  def set_combos
    @monofilamentos = Monofilamento.all
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliacao_sensitiva
      @avaliacao_sensitiva = AvaliacaoSensitiva.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def avaliacao_sensitiva_params
      params.require(:avaliacao_sensitiva).permit(:avaliacao_notificacao_id, :data, :dedao_direito, :indicador_d_ponta, :indicador_d, :mindinho_d_ponta, :mindinho_d, :mao_direita, :mao_d_costa, :dedao_esquerdo, :indicador_e_ponta, :indicador_e, :mindinho_e_ponta, :mindinho_e, :mao_esquerda, :mao_e_costa, :pe_direito, :pe_d_1_ponta, :pe_d_3_ponta, :pe_d_5_ponta, :pe_d_1, :pe_d_3, :pe_d_5, :pe_d_e1, :pe_d_e2, :pe_d_calcanhar, :pe_esquerdo, :pe_e_1_ponta, :pe_e_3_ponta, :pe_e_5_ponta, :pe_e_1, :pe_e_3, :pe_e_5, :pe_e_e1, :pe_e_e2, :pe_e_calcanhar,
                                                  marcacaos_attributes:[:id,:avaliacao_sensitiva_id,:imagem,:posicaox,:posicaoy,:membro,:_destroy])
    end
end

app/helpers/avaliacao_sensitivas_helper.rb
#Disponibiliza métodos para serem usados nas views
module AvaliacaoSensitivasHelper
end

app/views/avaliacao_sensitivas/_legenda_cores.html.erb
<% @monofilamentos.each do |m| %>
  <div class="row">
    <div class="col s2">
      <img src="/images/<%= m.nome.downcase %>.png" alt="">
    </div>
    <div class="col s10">
      <%= m.interpretacao %>
    </div>
  </div>
<% end %>

app/views/avaliacao_sensitivas/_legenda_marcas.html.erb
<div class="row">
  <div class="col s2">
    <img src="/images/reabsorcao.png" alt="">
  </div>
  <div class="col s10">
    Reabsorção
  </div>
</div>
<div class="row">
  <div class="col s2">
    <img src="/images/garramovel.png" alt="">
  </div>
  <div class="col s10">
    Garra Móvel
  </div>
</div>
<div class="row">
  <div class="col s2">
    <img src="/images/garrarigida.png" alt="">
  </div>
  <div class="col s10">
    Garra Rígida
  </div>
</div>
<div class="row">
  <div class="col s2">
    <img src="/images/ferida.png" alt="">
  </div>
  <div class="col s10">
    Ferida
  </div>
</div>

app/views/avaliacao_sensitivas/edit.html.erb
<div class="card-panel center">
	<h4>Formulário de Edição</h4>
</div>

<%= render 'form', avaliacao_sensitiva: @avaliacao_sensitiva %>

app/views/avaliacao_sensitivas/index.html.erb
<div class="card">  
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <%# f.text_field :name_cont, placeholder: "Pesquisar..." %>
      <%= f.submit "Filtrar", class:"btn" %>
      <% end %>
    </div>
  </div>
</div>

<table class="card striped responsive-table">
  <thead>
    <tr>
            <th>Avaliacao notificacao</th>
            <th>Data</th>
            <th>Dedao direito</th>
            <th>Indicador d ponta</th>
            <th>Indicador d</th>
            <th>Mindinho d ponta</th>
            <th>Mindinho d</th>
            <th>Mao direita</th>
            <th>Mao d costa</th>
            <th>Dedao esquerdo</th>
            <th>Indicador e ponta</th>
            <th>Indicador e</th>
            <th>Mindinho e ponta</th>
            <th>Mindinho e</th>
            <th>Mao esquerda</th>
            <th>Mao e costa</th>
            <th>Pe direito</th>
            <th>Pe d 1 ponta</th>
            <th>Pe d 3 ponta</th>
            <th>Pe d 5 ponta</th>
            <th>Pe d 1</th>
            <th>Pe d 3</th>
            <th>Pe d 5</th>
            <th>Pe d e1</th>
            <th>Pe d e1</th>
            <th>Pe d calcanhar</th>
            <th>Pe esquerdo</th>
            <th>Pe e 1 ponta</th>
            <th>Pe e 3 ponta</th>
            <th>Pe e 5 ponta</th>
            <th>Pe e 1</th>
            <th>Pe e 3</th>
            <th>Pe e 5</th>
            <th>Pe e e1</th>
            <th>Pe e e2</th>
            <th>Pe e calcanhar</th>
          </tr>
  </thead>

  <tbody>
    <% @avaliacao_sensitivas.each do |avaliacao_sensitiva| %>
    <tr>
              
          <td><%= link_to avaliacao_sensitiva.avaliacao_notificacao,avaliacao_sensitiva %></td>
        
              

          <td><%= avaliacao_sensitiva.data %></td>
        
              

          <td><%= avaliacao_sensitiva.dedao_direito %></td>
        
              

          <td><%= avaliacao_sensitiva.indicador_d_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.indicador_d %></td>
        
              

          <td><%= avaliacao_sensitiva.mindinho_d_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.mindinho_d %></td>
        
              

          <td><%= avaliacao_sensitiva.mao_direita %></td>
        
              

          <td><%= avaliacao_sensitiva.mao_d_costa %></td>
        
              

          <td><%= avaliacao_sensitiva.dedao_esquerdo %></td>
        
              

          <td><%= avaliacao_sensitiva.indicador_e_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.indicador_e %></td>
        
              

          <td><%= avaliacao_sensitiva.mindinho_e_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.mindinho_e %></td>
        
              

          <td><%= avaliacao_sensitiva.mao_esquerda %></td>
        
              

          <td><%= avaliacao_sensitiva.mao_e_costa %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_direito %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_1_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_3_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_5_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_1 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_3 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_5 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_e1 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_e1 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_d_calcanhar %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_esquerdo %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_1_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_3_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_5_ponta %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_1 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_3 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_5 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_e1 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_e2 %></td>
        
              

          <td><%= avaliacao_sensitiva.pe_e_calcanhar %></td>
        
          </tr>
    <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@avaliacao_sensitivas)  %>
</div>

<%= link_to '+ Cadastrar', new_avaliacao_sensitiva_path, class:"btn" %>

app/views/avaliacao_sensitivas/new.html.erb
<div class="card-panel center">
	<h4>Formulário de Cadastro</h4>
</div>

<%= render 'form', avaliacao_sensitiva: @avaliacao_sensitiva %>

app/views/avaliacao_sensitivas/show.html.erb
<div class="card-panel">
	
<p>
  <strong>Avaliacao notificacao:</strong>
  <%= @avaliacao_sensitiva.avaliacao_notificacao %>
</p>

<p>
  <strong>Data:</strong>
  <%= @avaliacao_sensitiva.data %>
</p>

  <% @avaliacao_sensitiva.sensitiva_images.each do |s| %>
      <img src="<%= s.imagem.url %>" alt="">
  <% end %>

</div>
<%= link_to 'Voltar', avaliacao_sensitivas_path, class:"btn" %>