config/routes.rb
Rails.application.routes.draw do


  resources :dant_faixa_etaria
  devise_for :users
  scope "/usuario" do
  resources :users do
    collection do
      get "home"
      get "alterar_senha"
    end
  end
  end
  resources :condutas
  resources :diagnosticos
  resources :sinais_sintomas
  resources :dermatologicas
  resources :recidivas
  resources :categoria_queixas
  resources :avaliacao_sensitivas do
    member do
      get "inserir_marcacao"
    end
    collection do
      get "remover_marcacao"
    end
  end
  resources :episodio_reacionals
  resources :avaliacao_neurologicas
  resources :classificacao_graus
  resources :avaliacao_notificacaos
  resources :esquema_substitutivos
  resources :contato_avaliacaos
  resources :bcgs
  resources :notificacao_contatos
  resources :dados_clinicos
  resources :notificacaos do
    collection do
      get 'home'
      get 'avaliacao_pendente'
    end
    member do
      get "recidiva"
    end
  end
  resources :pacientes do
    collection do
      get "mapa"
    end
  end
  resources :medicamentos
  resources :queixas
  resources :monofilamentos
  resources :ocupacaos
  resources :cidades

  resources :escala_parts
  resources :escala_salsas
  resources :monthly_reports

  scope "/dant" do
    resources :dant_questions
    resources :dant_requests do
      member do
        get "enviar"
        get "faixa_etaria"
        get "alterar_status"
      end
      collection do
        get "dashboard"
        get "cidade_change"
      end
    end
    resources :dant_responsavel_programs
    resources :dant_regions
    resources :dant_pacients


  end

  scope "/imunizacao" do
    resources :imunizacao_encerramentos
    resources :imunizacao_esquemas do
      member do
        get "novo_encerramento"
        get "nao_aplicado"
      end
    end
    resources :imunizacao_imunobiologicos do
      member do
        get "nova_dose"
        get "indeferir"
      end
    end
    resources :imunizacao_vacinas do
      member do
        get "retornarIndicacoes"
      end
      collection do
        get "relatorio"
      end
    end
    resources :imunizacao_solicitacaos
    resources :imunizacao_indications do
      member do
        get "retornar_vacinas"
      end
    end
  end

  scope  "/dst" do
    resources :dst_questionarios
    resources :dst_movimentacaos do
      collection do
        get "atender"
        get "finalizar_atendimento"
      end
    end
    resources :dst_solicitacao_produtos
    resources :dst_solicitacaos do
      member do
        get "autorizar"
        get "recusar"
      end
      collection do
        get "mapa"
      end
    end
    resources :dst_lotes
    resources :dst_locals
    resources :dst_produtos do
      member do
        get "lotes_ajax"
      end
    end
  end

  root "users#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/imunizacao/imunizacao_vacina.rb
# == Schema Information
#
# Table name: imunizacao_vacinas
#
#  id         :integer          not null, primary key
#  nome       :string
#  descricao  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ImunizacaoVacina < ApplicationRecord
  has_many :imunizacao_vacina_indications
  has_many :imunizacao_indications, through: :imunizacao_vacina_indications
  #
  #accepts_nested_attributes_for :imunizacao_indications, allow_destroy: true


  #Método que retorna o nome do objeto
  def to_s
    self.nome
  end

  #Método que retorna um array para ser utilizado nos combos
  def self.to_select
    all.order(:nome).map{|a| ["#{a}", a.id]}
  end

end

app/controllers/imunizacao_vacinas_controller.rb
#Classe que controla as açoes da ImunizacaoVacina
class ImunizacaoVacinasController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_imunizacao_vacina, only: [:show, :edit, :update, :destroy,:retornarIndicacoes]

  # GET /imunizacao_vacinas
  def index
    @q = ImunizacaoVacina.all.order(nome: :asc).ransack(params[:q])
    @imunizacao_vacinas = @q.result.page(params[:page])
  end

  # GET /imunizacao_vacinas/1
  def show
  end

  # GET /imunizacao_vacinas/new
  def new
    @imunizacao_vacina = ImunizacaoVacina.new
  end

  # GET /imunizacao_vacinas/1/edit
  def edit
  end


  def relatorio
    @q = ImunizacaoSolicitacao.includes(:imunobiologicos,:imunizacao_esquemas,:imunizacao_encerramentos).all.order(created_at: :desc).ransack(params[:q])


    @imunizacao_solicitacaos = @q.result.page(params[:page])
  end

  #Método que retorna as indicacoes da vacina
  def retornarIndicacoes
    @combo = params[:combo]
    @indicacoes = @imunizacao_vacina.imunizacao_indications.order(:descricao)
  end

  # POST /imunizacao_vacinas
  def create
    @imunizacao_vacina = ImunizacaoVacina.new(imunizacao_vacina_params)

    if @imunizacao_vacina.save
      redirect_to @imunizacao_vacina, notice: 'Imunizacao vacina was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /imunizacao_vacinas/1
  def update
    if @imunizacao_vacina.update(imunizacao_vacina_params)
      redirect_to @imunizacao_vacina, notice: 'Imunizacao vacina was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /imunizacao_vacinas/1
  def destroy
    @imunizacao_vacina.destroy
    redirect_to imunizacao_vacinas_url, notice: 'Imunizacao vacina was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imunizacao_vacina
      @imunizacao_vacina = ImunizacaoVacina.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def imunizacao_vacina_params
      params.require(:imunizacao_vacina).permit(:nome, :descricao, imunizacao_indications_attributes:[:id,:descricao,:imunizacao_vacina_id, :_destroy])
    end
end

app/helpers/imunizacao_vacinas_helper.rb
#Disponibiliza métodos para serem usados nas views
module ImunizacaoVacinasHelper
end

app/views/imunizacao_vacinas/_form.html.erb
<%= nested_form_for(imunizacao_vacina) do |f| %>
  <% if imunizacao_vacina.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5>Resolva os problemas a seguir antes de Salvar:</h5>

      <ul>
      <% imunizacao_vacina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label :nome %>
    <%= f.text_field :nome %>
    
  </div>

  <div class="input-field">

    <%= f.label :descricao %>
    <%= f.text_area :descricao %>
    
  </div>

<!--  <div class="card-panel">-->
<!--    <h4 class="header2">Indicações</h4>-->
    <%#= f.fields_for :imunizacao_indications do |i| %>
<!--      <div class="card-panel">-->
        <%#= i.label :descricao, "Descrição" %>
        <%#= i.text_field :descricao %>
        <%#= i.link_to_remove "Apagar", class: "btn red" %>

<!--      </div>-->
    <%# end %>
    <%#= f.link_to_add "Inserir", :imunizacao_indications, class: :btn %>
<!--  </div>-->

</div>
  <div class="actions">
    <%= f.submit "Salvar", class:"btn" %>
  </div>
<% end %>

app/views/imunizacao_vacinas/_indicacoes.html.erb
<option></option>
<%= items.each do |item| %>
  <option value=<%= item.id %> ><%= item.descricao %></option>
<% end %>

app/views/imunizacao_vacinas/edit.html.erb
<div class="card-panel center">
	<h4>Formulário de Edição</h4>
</div>

<%= render 'form', imunizacao_vacina: @imunizacao_vacina %>

app/views/imunizacao_vacinas/index.html.erb
<h1 class="center-align">Imunobiológicos</h1>
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <%= f.text_field :nome_cont, placeholder: "Pesquisar..." %>
      <%= f.submit "Filtrar", class:"btn" %>
      <% end %>
    </div>
  </div>
</div>

<table class="card striped responsive-table">
  <thead>
    <tr>
            <th>Nome</th>
            <th>Descricao</th>
          </tr>
  </thead>

  <tbody>
    <% @imunizacao_vacinas.each do |imunizacao_vacina| %>
    <tr>
              
          <td><%= link_to imunizacao_vacina.nome,imunizacao_vacina %></td>
        
              

          <td><%= imunizacao_vacina.descricao %></td>
        
          </tr>
    <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@imunizacao_vacinas)  %>
</div>

<%= link_to '+ Cadastrar', new_imunizacao_vacina_path, class:"btn" %>

app/views/imunizacao_vacinas/new.html.erb
<div class="card-panel center">
	<h4>Formulário de Cadastro</h4>
</div>

<%= render 'form', imunizacao_vacina: @imunizacao_vacina %>

app/views/imunizacao_vacinas/relatorio.html.erb
<h1 class="center-align">Relatório de vacinas aplicadas e vacinas a aplicar</h1>
<div class="card" style="overflow: visible;">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show row">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
        <%= f.text_field :nome_paciente_or_nome_mae_or_status_or_municipio_atual_nome_cont, placeholder: "Paciente..." %>
        <div class="col s12 l6">
          <%= f.label :created_at_gteq, "Data da Solicitação (Início)" %>
          <%= f.text_field :created_at_gteq, class:"datetimepicker" %>
        </div>
        <div class="col s12 l6">
          <%= f.label :created_at_lteq, "Data da Solicitação (Término)" %>
          <%= f.text_field :created_at_lteq, class:"datetimepicker"%>
        </div>
        <div class="col s12">
          <%= f.label :municipio_id_eq, "Município" %>
          <%= f.select :municipio_id_eq, Cidade.to_select, {prompt: true}  %>
        </div>
        <%= f.submit "Filtrar", class:"btn" %>

      <% end %>
    </div>
  </div>
</div>


<% @imunizacao_solicitacaos.each do |s| %>
  <div class="card-panel">
  <div class="row">
    <div class="col 12 l4">
      <label for="">Paciente:</label>
      <%= s.nome_paciente %>
    </div>
    <div class="col 12 l4">
      <label for="">Município</label>
      <%= s.municipio %>
    </div>
  </div>
  <div class="row">
    <div class="col s12 l6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Vacinas aplicadas</span>
          <table>
            <thead>
            <tr>
              <th>Vacina</th>
              <th>Dose</th>
              <th>Dt aplicação</th>
              <th>Lote dist.</th>
              <th>Lote aplic.</th>
            </tr>
            </thead>
            <tbody>
            <% s.imunizacao_esquemas.where(status: :concluido).each do |dose| %>
            <tr>
              <td><%= dose.imunizacao_imunobiologico %></td>
              <td><%= dose.dose %></td>
              <td><%= dose.imunizacao_encerramentos.last.data_administracao if dose.imunizacao_encerramentos.last.present?   %></td>
              <td><%= dose.lote   %></td>
              <td><%= dose.imunizacao_encerramentos.last.lote if dose.imunizacao_encerramentos.last.present?   %></td>
            </tr>

            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col s12 l6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Vacinas a aplicar</span>
          <table>
            <thead>
            <tr>
              <th>Vacina</th>
              <th>Dose</th>
              <th>Esquema</th>

            </tr>
            </thead>
            <tbody>
            <% s.imunizacao_esquemas.where(status: nil).each do |dose| %>
              <tr>
                <td><%= dose.imunizacao_imunobiologico %></td>
                <td><%= dose.dose %></td>
                <td><%= dose.esquema  %></td>

              </tr>

            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  </div>
<% end %>

app/views/imunizacao_vacinas/retornarIndicacoes.js.erb
$("#indicacao_<%= @combo %>").empty().append('<%= escape_javascript(render partial:"indicacoes", locals:{items:@indicacoes})%>');

app/views/imunizacao_vacinas/show.html.erb
<div class="card-panel">
	
<p>
  <strong>Nome:</strong>
  <%= @imunizacao_vacina.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @imunizacao_vacina.descricao %>
</p>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Indicações</span>
      <% @imunizacao_vacina.imunizacao_indications.each  do |i| %>
        <p><%= i.descricao %></p>
      <% end %>
    </div>
  </div>

</div>
<%= link_to 'Voltar', imunizacao_vacinas_path, class:"btn" %>