config/routes.rb
Rails.application.routes.draw do


  resources :dant_faixa_etaria
  devise_for :users
  scope "/usuario" do
  resources :users do
    collection do
      get "home"
      get "alterar_senha"
    end
  end
  end
  resources :condutas
  resources :diagnosticos
  resources :sinais_sintomas
  resources :dermatologicas
  resources :recidivas
  resources :categoria_queixas
  resources :avaliacao_sensitivas do
    member do
      get "inserir_marcacao"
    end
    collection do
      get "remover_marcacao"
    end
  end
  resources :episodio_reacionals
  resources :avaliacao_neurologicas
  resources :classificacao_graus
  resources :avaliacao_notificacaos
  resources :esquema_substitutivos
  resources :contato_avaliacaos
  resources :bcgs
  resources :notificacao_contatos
  resources :dados_clinicos
  resources :notificacaos do
    collection do
      get 'home'
      get 'avaliacao_pendente'
    end
    member do
      get "recidiva"
    end
  end
  resources :pacientes do
    collection do
      get "mapa"
    end
  end
  resources :medicamentos
  resources :queixas
  resources :monofilamentos
  resources :ocupacaos
  resources :cidades

  resources :escala_parts
  resources :escala_salsas
  resources :monthly_reports

  scope "/dant" do
    resources :dant_questions
    resources :dant_requests do
      member do
        get "enviar"
        get "faixa_etaria"
        get "alterar_status"
      end
      collection do
        get "dashboard"
        get "cidade_change"
      end
    end
    resources :dant_responsavel_programs
    resources :dant_regions
    resources :dant_pacients


  end

  scope "/imunizacao" do
    resources :imunizacao_encerramentos
    resources :imunizacao_esquemas do
      member do
        get "novo_encerramento"
        get "nao_aplicado"
      end
    end
    resources :imunizacao_imunobiologicos do
      member do
        get "nova_dose"
        get "indeferir"
      end
    end
    resources :imunizacao_vacinas do
      member do
        get "retornarIndicacoes"
      end
      collection do
        get "relatorio"
      end
    end
    resources :imunizacao_solicitacaos
    resources :imunizacao_indications do
      member do
        get "retornar_vacinas"
      end
    end
  end

  scope  "/dst" do
    resources :dst_questionarios
    resources :dst_movimentacaos do
      collection do
        get "atender"
        get "finalizar_atendimento"
      end
    end
    resources :dst_solicitacao_produtos
    resources :dst_solicitacaos do
      member do
        get "autorizar"
        get "recusar"
      end
      collection do
        get "mapa"
      end
    end
    resources :dst_lotes
    resources :dst_locals
    resources :dst_produtos do
      member do
        get "lotes_ajax"
      end
    end
  end

  root "users#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dant_request.rb
# == Schema Information
#
# Table name: dant_requests
#
#  id                                 :integer          not null, primary key
#  qtd_hipertensos                    :integer
#  atendimento_hipertensos            :integer
#  qtd_obitos_hipertensos             :integer
#  qtd_diabeticos                     :integer
#  atendimento_diabeticos             :integer
#  qtd_obitos_diabeticos              :integer
#  qtd_diabeticos_hipertencos         :integer
#  atendimento_diabeticos_hipertensos :integer
#  qtd_tratamento_hemodialise         :integer
#  qtd_nph                            :integer
#  qtd_frascos_nph                    :integer
#  qtd_regular                        :integer
#  qtd_frascos_regular                :integer
#  qtd_analoga                        :integer
#  qtd_frascos_analoga                :integer
#  qtd_tabagista                      :integer
#  qtd_atendimento_tabagista          :integer
#  qtd_etilista                       :integer
#  qtd_atendimento_etilista           :integer
#  qtd_obesos                         :integer
#  qtd_obesidade_1                    :integer
#  qtd_obesidate_2                    :integer
#  qtd_obesidade_3                    :integer
#  mes                                :integer
#  dant_responsavel_program_id        :integer
#  cidade_id                          :integer
#  status                             :string
#  created_at                         :datetime         not null
#  updated_at                         :datetime         not null
#  ano                                :integer
#  soma_participacoes                 :integer
#  data_envio                         :datetime
#  qtd_nph_calculada                  :integer
#  qtd_regular_calculada              :integer
#  qtd_analoga_calculada              :integer
#  justificativa                      :text
#  qtd_nph_caneta                     :integer
#  qtd_frascos_nph_caneta             :integer
#  qtd_regular_caneta                 :integer
#  qtd_frascos_regular_caneta         :integer
#
# Indexes
#
#  index_dant_requests_on_cidade_id                    (cidade_id)
#  index_dant_requests_on_dant_responsavel_program_id  (dant_responsavel_program_id)
#
# Foreign Keys
#
#  fk_rails_...  (cidade_id => cidades.id)
#  fk_rails_...  (dant_responsavel_program_id => dant_responsavel_programs.id)
#

class DantRequest < ApplicationRecord
  belongs_to :dant_responsavel_program
  belongs_to :cidade, dependent: :destroy
  has_many :dant_request_pacients, dependent: :destroy
  has_many :dant_pacients, through: :dant_request_pacients
  has_many :dant_faixa_etarias, class_name: "DantFaixaEtarium"
  has_one :dant_region, through: :cidade

  accepts_nested_attributes_for :dant_request_pacients, allow_destroy: true
  accepts_nested_attributes_for :dant_faixa_etarias, allow_destroy: true

  extend Enumerize

  enumerize :status, in: [:cadastrada,:solicitado, :deferido,:indeferido,:entregue], predicates: true

  before_create :set_status
  after_create :set_pacientes

  def set_pacientes
    pacientes = DantPacient.where(cidade_id: self.cidade_id).where.not(obito: true)
    pacientes.each do |p|
      pac = DantRequestPacient.new(dant_request_id: self.id,dant_pacient_id:p.id, idade: p.idade, hipertenso: p.hipertenso, diabetico: p.diabetico,sexo: p.sexo_value)
      pac.save
    end
  end


  #Método que seta o status da solicitação
  def set_status
    self.status = :cadastrada
    if self.mes == 12
      if DateTime.now.month <= 2
        self.ano = Date.today.year - 1
      elsif Date.today.month == 12
        self.ano = Date.today.year
      end

    else
      self.ano = Date.today.year
    end
  end

  #Método que calcula a quantidade de frascos a serem fornecidos
  def calcular_quantidades
    if self.mes == 3#março
      if self.data_envio.month <= 3
        self.qtd_nph_calculada = self.qtd_frascos_nph * 3 #quantidade para 3 meses
        self.qtd_regular_calculada = self.qtd_frascos_regular * 3 #quantidade para 3 meses
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * 3 #quantidade para 3 meses
      else
        #utiliza 6 no calculo como referência ao mês de junho
        self.qtd_nph_calculada = self.qtd_frascos_nph * (6 - self.data_envio.month)  #quantidade para meses restantes
        self.qtd_regular_calculada = self.qtd_frascos_regular * (6 - self.data_envio.month) #quantidade para  meses restantes
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * (6 - self.data_envio.month) #quantidade para meses restantes
      end
    elsif self.mes == 6#junho
      if self.data_envio.month <= 6
        self.qtd_nph_calculada = self.qtd_frascos_nph * 3 #quantidade para 3 meses
        self.qtd_regular_calculada = self.qtd_frascos_regular * 3 #quantidade para 3 meses
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * 3 #quantidade para 3 meses
      else
        #utiliza 9 no calculo como referência ao mês de setembro
        self.qtd_nph_calculada = self.qtd_frascos_nph * (9 - self.data_envio.month)  #quantidade para meses restantes
        self.qtd_regular_calculada = self.qtd_frascos_regular * (9 - self.data_envio.month) #quantidade para  meses restantes
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * (9 - self.data_envio.month) #quantidade para meses restantes
      end
    elsif self.mes == 9 #setembro
      if self.data_envio.month <= 9
        self.qtd_nph_calculada = self.qtd_frascos_nph * 3 #quantidade para 3 meses
        self.qtd_regular_calculada = self.qtd_frascos_regular * 3 #quantidade para 3 meses
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * 3 #quantidade para 3 meses
      else
        #utiliza 12 no calculo como referência ao mês de dezembro
        self.qtd_nph_calculada = self.qtd_frascos_nph * (12 - self.data_envio.month)  #quantidade para meses restantes
        self.qtd_regular_calculada = self.qtd_frascos_regular * (12 - self.data_envio.month) #quantidade para  meses restantes
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * (12 - self.data_envio.month) #quantidade para meses restantes
      end
    else #dezembro
      if self.data_envio.month == 12
        self.qtd_nph_calculada = self.qtd_frascos_nph * 3 #quantidade para 3 meses
        self.qtd_regular_calculada = self.qtd_frascos_regular * 3 #quantidade para 3 meses
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * 3 #quantidade para 3 meses
      else
        #utiliza 3 no calculo como referência ao mês de março
        self.qtd_nph_calculada = self.qtd_frascos_nph * (3 - self.data_envio.month)  #quantidade para meses restantes
        self.qtd_regular_calculada = self.qtd_frascos_regular * (3 - self.data_envio.month) #quantidade para  meses restantes
        #self.qtd_analoga_calculada = self.qtd_frascos_analoga * (3 - self.data_envio.month) #quantidade para meses restantes
      end
    end

  end
end

app/helpers/dant_requests_helper.rb
#Disponibiliza métodos para serem usados nas views
module DantRequestsHelper
end

app/views/dant_requests/cidade_change.js.erb
console.log("renderizando");
$("#dant_request_qtd_nph").val(<%= @qtd_nph  %>);
$("#dant_request_qtd_frascos_nph").val(<%= @qtd_frascos_nph %>);
$("#dant_request_qtd_nph_caneta").val(<%= @qtd_nph_caneta %>);
$("#dant_request_qtd_frascos_nph_caneta").val(<%= @qtd_frascos_nph_caneta %>);
$("#dant_request_qtd_regular").val(<%= @qtd_regular  %>);
$("#dant_request_qtd_frascos_regular").val(<%= @qtd_frascos_regular %>);
$("#dant_request_qtd_regular_caneta").val(<%= @qtd_regular_caneta %>);
$("#dant_request_qtd_frascos_regular_caneta").val(<%=@qtd_frascos_regular_caneta  %>);

app/views/dant_requests/edit.html.erb
<div class="card-panel center">
	<h4>Formulário de Edição</h4>
</div>

<%= render 'form', dant_request: @dant_request %>

app/views/dant_requests/index.html.erb
<div class="card">
  <h1 class="center-align">Solicitações</h1>
</div>
<div class="card" style="overflow: visible;">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
          <div class="row">
            <div class="col l3 s12">
              <%= f.label "Mês" %>
              <%= f.select :mes_eq, [["MARÇO" , 3],["JUNHO" , 6],["SETEMBRO" , 9],["DEZEMBRO" , 12]],{prompt: "Todos os Meses"} %>

            </div>

            <div class="col l3 s12">
              <%= f.label "Ano" %>
              <%= f.select :ano_eq, DantRequest.distinct.pluck(:ano),{prompt: "Todos os Anos"} %>

            </div>
            <div class="col l3 s12">
              <%= f.label "Município" %>
              <%= f.select :cidade_id_eq, @cidades,{prompt: "Todo o Estado",include_blank: true},{class:"browser-default chosen-select"} %>

            </div>
            <div class="col l3 s12">
              <%= f.label "Região" %>
              <%= f.select :dant_region_id_eq, @regioes,{prompt: "Todas as Regiões",include_blank: true},{class:"browser-default chosen-select"} %>

            </div>
          </div>
          <%# f.text_field :name_cont, placeholder: "Pesquisar..." %>
          <%= f.submit "Filtrar", class:"btn" %>
          <%= link_to "Limpar", dant_requests_path , class:"btn red" %>
      <% end %>
    </div>
  </div>
</div>


<table class="card striped responsive-table">
  <thead>
  <tr>

    <th>Mês</th>
    <th>Ano</th>
    <th>Responsável</th>
    <th>Cidade</th>
    <th>Status</th>
    <th>Ações</th>
  </tr>
  </thead>

  <tbody>
  <% @dant_requests.each do |dant_request| %>
      <tr>
        <td><%= dant_request.mes %></td>
        <td><%= dant_request.ano %></td>
        <td><%= dant_request.dant_responsavel_program %></td>
        <td><%= dant_request.cidade %></td>
        <td><%= dant_request.status %></td>
        <td><%= link_to "Visualizar", dant_request %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@dant_requests)  %>
</div>

<%= link_to '+ Cadastrar', new_dant_request_path, class:"btn" %>

app/views/dant_requests/new.html.erb
<div class="card-panel center">
	<h4>Formulário de Cadastro</h4>
</div>

<%= render 'form', dant_request: @dant_request %>

app/views/dant_requests/show.html.erb
<div class="card-panel">

  <% if @dant_request.status == "deferido" %>
      <div class="card-panel small white-text green">
      <h3 class="center-align">O Relatório Trimestral foi DEFERIDO.</h3>
          <h3 class="center-align">Leve a Posição de Estoque e a Guia de Requisição na DANT/ANEXO I para a liberação de insulinas</h3>
      </div>
  <% end %>

  <p>
    <strong>Mês:</strong>
    <%= @dant_request.mes %>/<%= @dant_request.ano %>
  </p>

  <p>
    <strong>Responsável pelo Programa:</strong>
    <%= @dant_request.dant_responsavel_program %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= @dant_request.cidade %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @dant_request.status.upcase %>
  </p>



  <% if @dant_request.status == "indeferido" %>
    <p>
      <strong>Indeferimento:</strong>
      <%= @dant_request.justificativa %>
    </p>
  <% end %>

  <div class="card-panel">
<table>
  <thead>
  <th>DADOS</th>
  <th>Quantidade</th>
  </thead>
  <tbody>
  <tr>
    <td><%= DantQuestion.find_by_pergunta(1) %></td>
    <td><%= @dant_request.qtd_hipertensos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(2) %></td>
    <td><%= @dant_request.atendimento_hipertensos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(3) %></td>
    <td><%= @dant_request.qtd_obitos_hipertensos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(4) %></td>
    <td><%= @dant_request.qtd_diabeticos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(5) %></td>
    <td><%= @dant_request.atendimento_diabeticos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(6) %></td>
    <td><%= @dant_request.qtd_obitos_diabeticos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(7) %></td>
    <td><%= @dant_request.qtd_diabeticos_hipertencos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(8) %></td>
    <td><%= @dant_request.atendimento_diabeticos_hipertensos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(9) %></td>
    <td><%= @dant_request.qtd_tratamento_hemodialise %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(10) %></td>
    <td><%= @dant_request.qtd_nph %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(11) %></td>
    <td><%= @dant_request.qtd_frascos_nph %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(23) %></td>
    <td><%= @dant_request.qtd_nph_caneta %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(24) %></td>
    <td><%= @dant_request.qtd_frascos_nph_caneta %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(12) %></td>
    <td><%= @dant_request.qtd_regular %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(13) %></td>
    <td><%= @dant_request.qtd_frascos_regular %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(25) %></td>
    <td><%= @dant_request.qtd_regular_caneta %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(26) %></td>
    <td><%= @dant_request.qtd_frascos_regular_caneta %></td>
  </tr>

  <!--<tr>
  <td>Qtd analoga:</td>
  <%#= @dant_request.qtd_analoga %>
</tr>

<tr>
  <td>Qtd frascos analoga:</td>
  <%#= @dant_request.qtd_frascos_analoga %>
</tr>-->

  <tr>
    <td><%= DantQuestion.find_by_pergunta(14) %></td>
    <td><%= @dant_request.qtd_tabagista %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(15) %></td>
    <td><%= @dant_request.qtd_atendimento_tabagista %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(16) %></td>
    <td><%= @dant_request.qtd_etilista %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(17) %></td>
    <td><%= @dant_request.qtd_atendimento_etilista %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(18) %></td>
    <td><%= @dant_request.qtd_obesos %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(19) %></td>
    <td><%= @dant_request.qtd_obesidade_1 %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(20) %></td>
    <td><%= @dant_request.qtd_obesidate_2 %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(21) %></td>
    <td><%= @dant_request.qtd_obesidade_3 %></td>
  </tr>

  <tr>
    <td><%= DantQuestion.find_by_pergunta(22) %></td>
    <td><%= @dant_request.soma_participacoes %></td>
  </tr>
  </tbody>
</table>
  </div>
  <% if @dant_request.status != :cadastrada %>
    <div class="card">
      <div class="card-content">
        <span class="card-title">Quantidade de frascos sugerido pelo sistemas</span>
        <table>
          <thead>
          <th>Tipo </th>
          <th>Quantidade</th>
          </thead>
          <tbody>
              <tr>
                <td>NPH</td>
                <td><%= @dant_request.qtd_nph_calculada %></td>
              </tr>
              <tr>
                <td>REGULAR</td>
                <td><%= @dant_request.qtd_regular_calculada %></td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <%= link_to "Planilha por Faixa Etária", faixa_etaria_dant_request_path(@dant_request), class:"btn", target:"_self" %>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Pacientes - INSULINA NPH</span>
        <table>
          <thead>
           <th>Nome</th>
           <th>Idade</th>
           <th>Frascos Diários</th>
           <th>Frascos Mensais</th>
          </thead>
          <tbody>
          <% @dant_request.dant_request_pacients.includes(:dant_doses).where(dant_doses: {tipo_insulina: "nph_frascos"}).each do |p| %>
            <tr>
              <td><%= p.dant_pacient %></td>
              <td><%= p.idade %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "nph_frascos").sum(:dose_diaria) %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "nph_frascos").sum(:frascos_mensais) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Pacientes - INSULINA NPH DE CANETA</span>
      <table>
        <thead>
        <th>Nome</th>
        <th>Idade</th>
        <th>Doses Diários</th>
        <th>Frascos Mensais</th>
        </thead>
        <tbody>
        <% @dant_request.dant_request_pacients.includes(:dant_doses).where(dant_doses: {tipo_insulina: "nph_de_caneta"}).each do |p| %>
            <tr>
              <td><%= p.dant_pacient %></td>
              <td><%= p.idade %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "nph_de_caneta").sum(:dose_diaria) %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "nph_de_caneta").sum(:frascos_mensais) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Pacientes - INSULINA REGULAR</span>
      <table>
        <thead>
        <th>Nome</th>
        <th>Idade</th>
        <th>Frascos Diários</th>
        <th>Frascos Mensais</th>
        </thead>
        <tbody>
        <% @dant_request.dant_request_pacients.includes(:dant_doses).where(dant_doses: {tipo_insulina: "regular_frascos"}).each do |p| %>
            <tr>
              <td><%= p.dant_pacient %></td>
              <td><%= p.idade %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "regular_frascos").sum(:dose_diaria) %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "regular_frascos").sum(:frascos_mensais) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Pacientes - INSULINA REGULAR DE CANETA</span>
      <table>
        <thead>
        <th>Nome</th>
        <th>Idade</th>
        <th>Frascos Diários</th>
        <th>Frascos Mensais</th>
        </thead>
        <tbody>
        <% @dant_request.dant_request_pacients.includes(:dant_doses).where(dant_doses: {tipo_insulina: "regular_de_caneta"}).each do |p| %>
            <tr>
              <td><%= p.dant_pacient %></td>
              <td><%= p.idade %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "regular_de_caneta").sum(:dose_diaria) %></td>
              <td><%= p.dant_pacient.dant_doses.where(tipo_insulina: "regular_de_caneta").sum(:frascos_mensais) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>
<%= link_to 'Voltar', dant_requests_path, class:"btn" %>
<%= link_to 'Enviar', enviar_dant_request_path(@dant_request), class:"btn green" if @dant_request.status == :cadastrada %>
<% if @dant_request.status != :cadastrada and ( current_user.administrador? || current_user.admin_dant?) %>
  <%= link_to "Deferir", alterar_status_dant_request_path(@dant_request, status: "deferido"), class:"btn green", target:"_self"%>
  <%#= link_to "Indeferir", alterar_status_dant_request_path(@dant_request, status: "indeferido"), class:"btn red", target:"_self"%>
    <a class="btn red modal-trigger" href="#modal_justificativa">Indeferir</a>
  <%= link_to "Entregar", alterar_status_dant_request_path(@dant_request, status: "entregue"), class:"btn blue", target:"_self"%>
<% end %>

<div id="modal_justificativa" class="modal">
  <div class="modal-content">
    <h4>Informe o motivo do indeferimento</h4>
    <%= form_for(@dant_request) do |f| %>
      <div class="input-field">
        <%= f.label :justificativa %>
        <%= f.text_area :justificativa,{class:"materialize-textarea"} %>
      </div>
        <%= f.hidden_field :status, value: "indeferido" %>
        <%= f.submit "Salvar", class:"btn", target:"_self" %>
    <% end %>
  </div>

</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $('.modal').modal();
    });
</script>